Add ApplicationDbContext
rarptr/PetBrothers pull request #6
Opened 2024-09-27 23:24 UTC by rarptr

2024-09-28 05:24 UTC, YaraOduvanchik requested changes

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/PaymentDetail.cs
> +        var paymentDetails = new PaymentDetail(title, description);
Нужно валидировать title и description

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/CommonDescription.cs
> +    public static Result<CommonDescription> Create(string value) => new CommonDescription(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Email.cs
> +    public static Result<Email> Create(string value) => new Email(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/BirthDate.cs
> +    public static Result<BirthDate> Create(DateOnly value) => new BirthDate(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Breed.cs
> +    public static Result<Breed> Create(string value) => new Breed(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Colour.cs
> +    public static Result<Colour> Create(string value) => new Colour(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/CurrentAddress.cs
> +    public static Result<CurrentAddress> Create(string value) => new CurrentAddress(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Description.cs
> +    public static Result<Description> Create(string value) => new Description(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/HealthInformation.cs
> +    public static Result<HealthInformation> Create(string value) => new HealthInformation(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Height.cs
> +    public static Result<Height> Create(float value) => new Height(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/IsCastrated.cs
> +    public static Result<IsCastrated> Create(bool value) => new IsCastrated(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/IsVaccinated.cs
> +    public static Result<IsVaccinated> Create(bool value) => new IsVaccinated(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Name.cs
> +    public static Result<Name> Create(string value) => new Name(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/OwnerPhoneNumber.cs
> +    public static Result<OwnerPhoneNumber> Create(string value) => new OwnerPhoneNumber(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Species.cs
> +    public static Result<Species> Create(string value) => new Species(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Weight.cs
> +    public static Result<Weight> Create(float value) => new Weight(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/PhoneNumber.cs
> +    public static Result<PhoneNumber> Create(string value) => new PhoneNumber(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/YearsExperience.cs
> +    public static Result<YearsExperience> Create(int value) => new YearsExperience(value);
Добавь валидацию

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/Pet.cs
> +    public Volunteer? Volunteer { get; set; }
Это убрать.

Мы будем взаимодействовать с животными через модель волонтёра, поэтому это не нужно

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.HasOne(p => p.Volunteer)
Убрать

2024-09-28 05:24 UTC, YaraOduvanchik commented on src/PetBrothers.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.Property(p => p.BirthDate)
Лучше просто сделать у поля DateTime просто, но и так можно

2024-09-28 21:48 UTC, rarptr commented on src/PetBrothers.Domain/Volunteers/Pets/IsCastrated.cs
> +    public static Result<IsCastrated> Create(bool value) => new IsCastrated(value);
какая может быть валидация для булевого значения?

2024-09-28 21:48 UTC, rarptr commented on src/PetBrothers.Domain/Volunteers/Pets/IsVaccinated.cs
> +    public static Result<IsVaccinated> Create(bool value) => new IsVaccinated(value);
какая может быть валидация для булевого значения?

2024-09-28 21:49 UTC, rarptr commented on src/PetBrothers.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.Property(p => p.BirthDate)
попробую использовать `DateOnly`, если возникнут проблемы, то перепишу на `DateTime`

2024-09-29 03:15 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/IsCastrated.cs
> +    public static Result<IsCastrated> Create(bool value) => new IsCastrated(value);
Извиняюсь, тогда сделай просто публичный конструктор, тут не нужен фабричный метод, если валидации нету

2024-09-29 03:15 UTC, YaraOduvanchik commented on src/PetBrothers.Domain/Volunteers/Pets/IsVaccinated.cs
> +    public static Result<IsVaccinated> Create(bool value) => new IsVaccinated(value);
Извиняюсь, тогда сделай просто публичный конструктор, тут не нужен фабричный метод, если валидации нету

2024-09-29 15:21 UTC, merged